include:
  - template: Jobs/Code-Quality.gitlab-ci.yml

stages:
  - build
  - test
  - staging

before_script:
  - - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - cd my-static-app-car
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME -f dockerfile .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - echo "build successful"

staging:
  stage: staging
  script:
    - cd my-static-app-car/
    - docker run -d -p 8080:80 --name app-car-staging $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - echo "Test application --> http://localhost:8080"
  dependencies:
    - build
  environment:
    name: staging
    url: http://localhost:8080
  only:
    - main
  when: on_success
