include:
  - template: Jobs/Code-Quality.gitlab-ci.yml

stages:
  - build
  - test
  - staging
  - production

before_script:
  - cd my-static-app-car
  - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - npm ci --quiet && npm cache clean --force
    - npm run build
    - mv dist ../public
  artifacts:
    paths:
      - public
    untracked: false
    when: on_success
    expire_in: "30 days"

staging:
  stage: staging
  script:
    - cp -r public/* $CI_PROJECT_DIR/staging
    - cd $CI_PROJECT_DIR/staging
    - npm install -g http-server
    - http-server -p 8080 &
    - echo "Staging server is running --> http://localhost:8080"
  dependencies:
    - build
  environment:
    name: staging
    url: http://localhost:8080
  when: on_success

pages:
  stage: production
  script:
    - echo "Deploying to production...."
  artifacts:
    paths:
      - public
  environment:
    name: production
    url: https://Lthat_h.gitlab.io/projet_docker_gitlab_ci_cd_new
  dependencies:
    - build
  only:
    - main
  when: manual
