# L'ancien Dockerfile sans le multistage
# REPOSITORY   TAG       IMAGE ID       CREATED          SIZE
# app-car      1.0       8440ddee3888   11 minutes ago   503MB

# Stage 1: Base image for development

FROM node:current-alpine as base
WORKDIR /app
COPY . .
RUN npm ci --quiet && npm cache clean --force

# Stage 2: Build stage

FROM base AS build 
WORKDIR /build
COPY --from=base /app ./
RUN npm run build

# Stage 3: Production image 

FROM nginx:stable-alpine as production
COPY --from=build /build/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]


LABEL maintainer="Lthat <hakim.afarmach@supdevinci-edu.fr>"
LABEL description="Optimisation de la première version avec un Dockerfile multi-stage"
LABEL version="2.0"
LABEL build_date="19/01/2024"
